import './globals.css'
import ClientLayout from '@/app/components/client-layout'

// 메타데이터는 서버 컴포넌트에서 사용
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  )
}
